### ISSUE TITLE
Better name?

### ISSUE THREAD

**Issue by cfilipov** [groue/ReactiveGRDB#1]
The "Reactive" in ReactiveGRDB implies [ReactiveSwift/ReactiveCocoa](https://github.com/ReactiveCocoa/ReactiveSwift) which is a different implementation of reactive programming than the one used in this repo (RxSwift). Would you be open to calling it "RxGRDB"? I think this would help reduce a lot of confusion for people (like me) who see the name and assume the other "reactive".

BTW, love where this is going, and +1 for choosing RxSwift.

**Comment by groue** [comment]
Hello @cfilipov  :-)

I'm new to reactive programming, so please forgive my clumsiness! I'm so new to RX I don't care yet about the RxSwift / ReactiveCocoa rivalry. It just happens that I met the great @fpillet, who gave a pretty good introduction to RxSwift.

But since I've started with RxSwift, RxGRDB may be a better name, you're right :-) I'll do that.

**Comment by cfilipov** [comment]
Thanks for making this project BTW. I'm fairly new to Rx myself, but so far it has been very productive for me. Looking forward to seeing how this goes.

**Comment by groue** [comment]
Done ! https://github.com/groue/RxGRDB
